# Generated by Django 6.0.2 on 2026-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.CharField(max_length=1000)),
                ('category_photo', models.ImageField(null=True, upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(default='general', max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
            ],
        ),
    ]
