# Generated by Django 6.0.2 on 2026-02-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
