# Generated by Django 6.0.2 on 2026-02-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=10)),
                ('id_image', models.ImageField(upload_to='ids/personal_id/')),
                ('professional_id_image', models.ImageField(upload_to='ids/worker_id/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.users')),
            ],
        ),
    ]
