# Generated by Django 6.0.2 on 2026-02-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_workerdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerDB',
        ),
    ]
