# Generated by Django 6.0.2 on 2026-02-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_workerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workerdb',
            name='username',
        ),
    ]
