# Generated by Django 6.0.2 on 2026-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_remove_workerdb_email_remove_workerdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('problem_title', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=50)),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='maintenance_images/')),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
            ],
        ),
    ]
