# Generated by Django 6.0.2 on 2026-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='is_urgent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
