# Generated by Django 6.0.2 on 2026-02-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_maintenancerequest_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
