# Generated by Django 6.0.2 on 2026-02-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='worker',
            field=models.CharField(max_length=50),
        ),
    ]
