# Generated by Django 6.0.2 on 2026-02-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_maintenancerequest_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
