# Generated by Django 6.0.2 on 2026-02-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_maintenancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='worker_id',
        ),
    ]
