# Generated by Django 6.0.2 on 2026-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_remove_maintenancerequest_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='worker_id',
            field=models.IntegerField(default=0),
        ),
    ]
