# Generated by Django 6.0.2 on 2026-02-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_maintenancerequest_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_urgent',
        ),
    ]
