# Generated by Django 6.0.2 on 2026-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_remove_maintenancerequest_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_urgent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
