# Generated by Django 6.0.2 on 2026-02-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_maintenancerequest_is_urgent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerDB',
        ),
    ]
