# Generated by Django 6.0.2 on 2026-02-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_workerdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
