# Generated by Django 6.0.2 on 2026-02-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_maintenancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='problem_image',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='problem_title',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='worker_id',
        ),
    ]
