# Generated by Django 6.0.2 on 2026-02-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_remove_maintenancerequest_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
