# Generated by Django 6.0.2 on 2026-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completed_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
