# Generated by Django 6.0.2 on 2026-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_alter_maintenancerequest_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='work_started_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
