# Generated by Django 6.0.2 on 2026-02-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_alter_maintenancerequest_work_started_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='payment_id',
            new_name='razorpay_order_id',
        ),
    ]
