# Generated by Django 6.0.2 on 2026-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0026_rename_payment_id_maintenancerequest_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdb',
            name='worker_image',
            field=models.ImageField(blank=True, upload_to='worker_photo'),
        ),
    ]
