# Generated by Django 6.0.2 on 2026-03-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0027_workerdb_worker_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='razorpay_order_id',
            new_name='payment',
        ),
    ]
