# Generated by Django 6.0.2 on 2026-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0028_rename_razorpay_order_id_maintenancerequest_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_urgent',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completed_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='work_started_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='worker',
            field=models.CharField(default='not assigned', max_length=50),
        ),
    ]
