# Generated by Django 6.0.2 on 2026-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0029_remove_maintenancerequest_is_urgent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='work_started_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
