# Generated by Django 6.0.2 on 2026-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0030_alter_maintenancerequest_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
