# Generated by Django 6.0.2 on 2026-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0031_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('benefits', models.TextField()),
            ],
        ),
    ]
