# Generated by Django 6.0.2 on 2026-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0032_subscriptiondb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiondb',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='subscriptiondb',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscriptiondb',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subscriptiondb',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='emergency_support',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='free_minor_repairs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_plans/'),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='inspections_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='response_time',
            field=models.IntegerField(blank=True, help_text='Service response time in hours', null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='seasonal_inspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondb',
            name='spare_parts_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondb',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
