# Generated by Django 6.0.2 on 2026-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_remove_subscriptiondb_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondb',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
