# Generated by Django 6.0.2 on 2026-03-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0034_subscriptiondb_plan_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondb',
            old_name='spare_parts_discount',
            new_name='discount',
        ),
    ]
