# Generated by Django 6.0.2 on 2026-03-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0035_rename_spare_parts_discount_subscriptiondb_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
