# Generated by Django 6.0.2 on 2026-03-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_userplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplans',
            name='payment',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
