# Generated by Django 6.0.2 on 2026-03-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0037_userplans_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondb',
            old_name='duration_months',
            new_name='duration',
        ),
    ]
