# Generated by Django 6.0.2 on 2026-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0038_rename_duration_months_subscriptiondb_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workerdb',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
