# Generated by Django 6.0.2 on 2026-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0039_alter_users_password_alter_workerdb_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdb',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
